### ISSUE TITLE
user can see their car

### ISSUE THREAD

**Issue by CooperKile** [CooperKile/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List
- [x] Create all necessary files for the project
- [x] Load a top down image of a car into the html 
- [x] Add styling to the page
- [x] Remove unnecessary css
