### ISSUE TITLE
user can turn their car

### ISSUE THREAD

**Issue by CooperKile** [CooperKile/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] add an event listener for a keydown on the arrow keys
- [x] query the dom for the image of the car
- [x] add css styling for rotating
- [x] add css classes to the html when keydown event happens
- [x] add a transition time to the rotation
- [x] remove unnecessary css
- [x] remove console logs
- [x] fix any bugs leftover
