### ISSUE TITLE
user can start their car

### ISSUE THREAD

**Issue by CooperKile** [CooperKile/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] listen for a keydown event on the spacebar
- [x] create a function for the event
- [x] add a location to cars x and y point
- [x] add absolute positioning on the image
- [x] use style property to change your car's top and left box offset styles.
- [x] inside function move the car every 16 milliseconds when the user presses space
- [x] remove any unused styling
- [x] fix any bugs
