### ISSUE TITLE
user can stop their car

### ISSUE THREAD

**Issue by CooperKile** [CooperKile/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] create a variable that holds a boolean
- [x] if the space key is pressed, update the boolean to true
- [ ] if the space key isn't pressed, update the boolean to false
- [ ] add a function that stops the car
- [ ] remove bugs 
- [ ] removed unused css
